services:
  solr:
    image: solr:9.8
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command: 
      - solr-precreate
      - example
    container_name: solr
    networks:
      - my_network
  
  java:
    build:
      context: .
      dockerfile: ./java/Dockerfile
    volumes:
      - type: bind
        source: ./java
        target: /app/java
      - type: bind
        source: ./data
        target: /app/data
    container_name: java
    tty: true
    depends_on:
      - solr
      - python
    networks:
      - my_network

  python:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    ports:
      - "5000:5000"
    container_name: python
    volumes:
      - type: bind
        source: ./python
        target: /app/python
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  data:
    name: "data"